title:                A Scorpio's Life
email:              nikunjj46@gmail.com
description:        Nikunj Jain's blog about Life, Universe and Everything
author:             Nikunj Jain
baseurl:            "/rock-nik.github.io"
url:                "rock-nik.github.io"
# Social Profiles
twitter_username:   Nikunjj95
github_username:    rock-nik
facebook_username:  Nikunjjain95
linkedin_username: rocknik
instagram_username: nikunj_jain_nj

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
